### PR TITLE
Delete tickets with no information.

### LINKED ISSUE #128: Remove tickets from db if they dont get mined
vspd will accept tickets which only exist in the mempool of its local dcrd instance. These tickets need to be removed from the vspd database if they are never mined, otherwise the background handler will continuously try to `getrawtransaction` for them and hit errors:

```
 /dcrd.log.154.gz:2020-06-10 16:59:01.032 [DBG] TXMP: Pruning expired transaction 4161acf257913a2326c373a5994ebffd36e8cbcd3da1de4cd7295efc7a9f5d35 from the mempool
```

```
2020-06-10 16:56:49.611 [DBG] API: Fee address created for new ticket: tktConfirmed=false, feeAddrIdx=2686, feeAddr=TsTwjb2BX1Mte7Lt2ug9pwuwzzUWhyv5Rgm, feeAmt=0.00860997 DCR, ticketHash=4161acf257913a2326c373a5994ebffd36e8cbcd3da1de4cd7295efc7a9f5d35
2020-06-10 16:56:49.678 [DBG] API: Fee tx received for ticket: minExpectedFee=0.00860997 DCR, feePaid=0.00860997 DCR, ticketHash=4161acf257913a2326c373a5994ebffd36e8cbcd3da1de4cd7295efc7a9f5d35
2020-06-10 16:59:01.098 [ERR]  BG: GetRawTransaction error: No information available about transaction 4161acf257913a2326c373a5994ebffd36e8cbcd3da1de4cd7295efc7a9f5d35
2020-06-10 16:59:43.957 [ERR]  BG: GetRawTransaction error: No information available about transaction 4161acf257913a2326c373a5994ebffd36e8cbcd3da1de4cd7295efc7a9f5d35
2020-06-10 17:01:57.300 [ERR]  BG: GetRawTransaction error: No information available about transaction 4161acf257913a2326c373a5994ebffd36e8cbcd3da1de4cd7295efc7a9f5d35
2020-06-10 17:04:25.326 [ERR]  BG: GetRawTransaction error: No information available about transaction 4161acf257913a2326c373a5994ebffd36e8cbcd3da1de4cd7295efc7a9f5d35
```

```
2020-06-12 13:37:18.505 [DBG]  DB: Opened database file /home/dcrd/.vspd/data/testnet3/vspd.db
2020-06-12 13:37:18.561 [INF] API: Listening on :3000
2020-06-12 13:37:18.665 [ERR]  BG: GetRawTransaction error: No information available about transaction 4161acf257913a2326c373a5994ebffd36e8cbcd3da1de4cd7295efc7a9f5d35
2020-06-12 13:37:18.666 [ERR]  BG: GetRawTransaction error: No information available about transaction ab4ade93b88193a23f957dfa85dd9e9373c2b4d3103aaf209b19ad390e35359a
2020-06-12 13:37:18.666 [ERR]  BG: GetRawTransaction error: No information available about transaction ec0d2fdc68fb884a81b385e8b0f0b618a0b3922304590be4a3f5d03ad155b659
2020-06-12 13:37:18.821 [INF]  BG: Subscribed for dcrd block notifications
```

### PR DESCRIPTION
**Pull request by jholdstock**
Closes #128

### CODE REVIEW

File: background/background.go [hunk 1]
```diff
@@ -76,9 +77,25 @@ func blockConnected() {
 	for _, ticket := range unconfirmed {
 		tktTx, err := dcrdClient.GetRawTransaction(ticket.Hash)
 		if err != nil {
-			log.Errorf("GetRawTransaction error: %v", err)
+			// Hitting this error probably indicates a tx which was never mined
+			// and has been removed from the mempool. For example, a ticket
+			// purchase tx close to an sdiff change, or a ticket purchase tx
+			// which expired. Remove it from the db.
+			if strings.Contains(err.Error(), "No information available about transaction") {
```
Comment (JoeGruffins) [inline background/background.go:84]: Does this also work?
```
import "github.com/decred/dcrd/dcrjson/v3"
...
if errors.Is(err, dcrjson.ErrNoTxInfo) {
...
```

Comment (jholdstock) [reply background/background.go:84]: I don't think this will work because `dcrjson.ErrNoTxInfo` is actually a different error. The one received by vspd has a different message which includes the transaction hash, and it also does not include the -5 code. There is some examples of the error in #128 

Its the same issue here https://github.com/decred/vspd/blob/master/rpc/dcrd.go#L105

dcrd does not include error codes in its rpc responses, just strings :(

Comment (JoeGruffins) [reply background/background.go:84]: Oh. That's confusing. Thanks for pointing those lines out.

Comment (jholdstock) [reply background/background.go]: I've just discovered that unlike `sendrawtransaction`, this RPC actually does return a proper code, so we can match on the code rather than the string. Updated the PR.
